---
# Get keys in this secret path and retrieve their latest versions
- name: Get Keys in Secret Path
  uri:
    url: "{{ rest_server_url }}/secret/paths/{{ secret_path | urlencode }}/keys"
    method: GET
    validate_certs: true
    client_cert: "{{ none if client_tls_cert is not defined else client_tls_cert }}"
    client_key: "{{ none if client_tls_key is not defined else client_tls_key }}"
    ca_path: "{{ none if ca_tls_path is not defined else ca_tls_path }}"
    timeout: "{{ api_timeout }}"
    headers:
      Authorization: "{{ authorization_header }}"
      Content-Type: "application/json"
    status_code: [200, 404]
  register: path_keys_result
  check_mode: false
  ignore_errors: true

- name: Get Latest Version for Each Key in Path
  uri:
    url: "{{ rest_server_url }}/secret/paths/{{ secret_path | urlencode }}/keys/{{ item | urlencode }}/versions/{{ secret_default_version }}"
    method: GET
    validate_certs: true
    client_cert: "{{ none if client_tls_cert is not defined else client_tls_cert }}"
    client_key: "{{ none if client_tls_key is not defined else client_tls_key }}"
    ca_path: "{{ none if ca_tls_path is not defined else ca_tls_path }}"
    timeout: "{{ api_timeout }}"
    headers:
      Authorization: "{{ authorization_header }}"
      Content-Type: "application/json"
    status_code: [200, 404]
  register: key_secret_results
  loop: "{{ path_keys_result.json | d([]) }}"
  check_mode: false
  ignore_errors: true
  no_log: true
  when:
    - path_keys_result.status == 200
    - path_keys_result.json is defined

- name: Build Current State Structure for Connect Secrets
  set_fact:
    secrets_list: "{{ secrets_list + [_secret_item] }}"
  loop: "{{ key_secret_results.results | d([]) }}"
  vars:
    _secret_item:
      path: "{{ secret_path }}"
      key: "{{ item.item }}"
      secret: "{{ item.json.secret | default('') }}"
      version: "{{ item.json.version | default(1) }}"
      created_time: "{{ item.json.created_time | default('') }}"
      modified_time: "{{ item.json.modified_time | default('') }}"
      metadata:
        topic: "{{ secret_topic }}"
        group_id: "{{ secret_group_id }}"
        connect_cluster: "{{ connect_cluster_id }}"
        kafka_cluster: "{{ kafka_cluster_id }}"
  no_log: true
  when:
    - item.status == 200
    - "'json' in item"
    - item.json.secret is defined
