---
# make out delta operation from the existing and intended secrets setup
# input secrets_current - current state; secrets - desired state
- debug:
    msg:
      - "Current state>{{ secrets_current }}"
      - "Desired state>{{ secrets }}"
    verbosity: 2

- name: Initialize variables
  set_fact:
    secrets_to_add: []
    secrets_to_update: []
    secrets_to_delete: []

- name: To add
# check the secrets to add - compare path/key combinations
  set_fact:
    secrets_to_add: "{{ secrets_to_add + [item] }}"
  loop: "{{ secrets }}"
  when: item_identifier in secrets_to_add_identifiers
  vars:
    item_identifier: "{{ item.path }}/{{ item.key }}"
    current_identifiers: "{{ secrets_current | map(attribute='path') | zip(secrets_current | map(attribute='key')) | map('join', '/') | list }}"
    desired_identifiers: "{{ secrets | map(attribute='path') | zip(secrets | map(attribute='key')) | map('join', '/') | list }}"
    secrets_to_add_identifiers: "{{ desired_identifiers | difference(current_identifiers) }}"

- name: To remove
# only check against the path/key combinations, with protection filter
  set_fact:
    secrets_to_delete: "{{ current_secrets_for_delete }}"
  vars:
    current_identifiers: "{{ secrets_current | map(attribute='path') | zip(secrets_current | map(attribute='key')) | map('join', '/') | list }}"
    desired_identifiers: "{{ secrets | map(attribute='path') | zip(secrets | map(attribute='key')) | map('join', '/') | list }}"
    identifiers_to_delete: "{{ current_identifiers | difference(desired_identifiers) }}"
    current_secrets_for_delete: "{{ secrets_current | selectattr('path', 'in', identifiers_to_delete | map('split', '/') | map('first') | unique) }}"
  when: secrets_current | length > 0

- name: Filter Protected Secrets from Deletion
  set_fact:
    secrets_to_delete: "{{ secrets_to_delete | rejectattr('path', 'regex', secret_protected) | list }}"
  when:
    - secret_protected != ""
    - secrets_to_delete | length > 0

- name: To update
# check for secrets that exist but have different values
  set_fact:
    secrets_to_update: "{{ secrets_to_update + [item] }}"
  loop: "{{ secrets }}"
  when:
    - secrets_current | length > 0
    - item_identifier in current_identifiers
    - item_identifier not in secrets_to_delete_identifiers
    - current_secret.secret != item.secret
  vars:
    item_identifier: "{{ item.path }}/{{ item.key }}"
    current_identifiers: "{{ secrets_current | map(attribute='path') | zip(secrets_current | map(attribute='key')) | map('join', '/') | list }}"
    secrets_to_delete_identifiers: "{{ secrets_to_delete | map(attribute='path') | zip(secrets_to_delete | map(attribute='key')) | map('join', '/') | list }}"
    current_secret: "{{ secrets_current | selectattr('path', 'equalto', item.path) | selectattr('key', 'equalto', item.key) | first }}"

- debug:
    var: secrets_to_add
    verbosity: 2
- debug:
    var: secrets_to_delete
    verbosity: 2
- debug:
    var: secrets_to_update
    verbosity: 2
