---
# Low level secret operations - using Connect Secret Registry API
# update secret creates a new version of an existing key in a path
- name: Update secrets in Connect Secret Registry (create new version)
  uri:
    url: "{{ rest_server_url }}/secret/paths/{{ item.path | urlencode }}/keys/{{ item.key | urlencode }}/versions"
    method: POST
    validate_certs: true
    client_cert: "{{ none if client_tls_cert is not defined else client_tls_cert }}"
    client_key: "{{ none if client_tls_key is not defined else client_tls_key }}"
    ca_path: "{{ none if ca_tls_path is not defined else ca_tls_path }}"
    timeout: "{{ api_timeout }}"
    headers:
      Authorization: "{{ authorization_header }}"
      Content-Type: application/json
    body_format: json
    body:
      secret: "{{ item.secret }}"
    status_code: [200, 404]
  register: result
  failed_when: result.status not in [200, 404]
  changed_when: result.status == 200
  no_log: true
  loop: "{{ secrets_in | flatten(levels=1) }}"
