---
# build a configuration structure from current state of secrets in the Connect Secret Registry
- name: Get All Secret Paths from Connect Secret Registry
  uri:
    url: "{{ rest_server_url }}/secret/paths"
    method: GET
    validate_certs: true
    client_cert: "{{ none if client_tls_cert is not defined else client_tls_cert }}"
    client_key: "{{ none if client_tls_key is not defined else client_tls_key }}"
    ca_path: "{{ none if ca_tls_path is not defined else ca_tls_path }}"
    timeout: "{{ api_timeout }}"
    headers:
      Authorization: "{{ authorization_header }}"
      Content-Type: "application/json"
    status_code: [200, 404]
  register: secret_paths_result
  check_mode: false

- name: Initialize secrets list
  set_fact:
    secrets_list: []

- name: Process Each Secret Path
  include_tasks: tasks/secrets_dump_tasks.yml
  loop: "{{ secret_paths_result.json | d([]) }}"
  when:
    - secret_paths_result.status == 200
    - secret_paths_result.json is defined
    - secret_path | regex_search(secret_whitelist)
    - not (secret_path | regex_search(secret_protected))
  loop_control:
    loop_var: secret_path

- name: Set final secrets_current from collected secrets
  set_fact:
    secrets_current: "{{ secrets_list }}"
  no_log: true
