---
# Low level secret operations - using Connect Secret Registry API
# delete removes all versions of a key (or can delete specific version)
- name: Delete Secrets from Connect Secret Registry
  uri:
    url: "{{ rest_server_url }}/secret/paths/{{ item.path | urlencode }}/keys/{{ item.key | urlencode }}"
    method: DELETE
    validate_certs: true
    client_cert: "{{ none if client_tls_cert is not defined else client_tls_cert }}"
    client_key: "{{ none if client_tls_key is not defined else client_tls_key }}"
    ca_path: "{{ none if ca_tls_path is not defined else ca_tls_path }}"
    timeout: "{{ api_timeout }}"
    headers:
      Authorization: "{{ authorization_header }}"
      Content-Type: "application/json"
    status_code: [200, 404]
  register: result
  failed_when: result.status not in [200, 404]
  changed_when: result.status == 200
  loop: "{{ secrets_in }}"
  no_log: true
