---
- set_fact:
    sr_user: "{{ schema_registry_ldap_user if schema_registry_ldap_user is defined else sasl_plain_users.schema_registry.principal }}"

- set_fact:
    sr_user_password: "{{ schema_registry_ldap_password if schema_registry_ldap_password is defined else sasl_plain_users.schema_registry.password }}"
