---
- name: "Set compatibility for {{ itemin._subject_name }}"
  ansible.builtin.include_tasks: _schema_set_compatibility.yml
  vars:
    _subject_name: "{{ itemin._subject_name }}"
    _compatibility: "{{ itemin._compatibility }}"
  when:
    - itemin._schema_update | bool
    - not (itemin._schema_delete_all | bool or itemin._schema_delete_curr | bool)

- name: "Register schema for {{ itemin._subject_name }}"
  ansible.builtin.include_tasks: _schema_register.yml
  vars:
    _subject_name: "{{ itemin._subject_name }}"
    _schema_file_src_path: "{{ itemin._schema_file_src_path }}"
    _schema_type: "{{ itemin._schema_type }}"
  when:
    - itemin._schema_update | bool
    - not (itemin._schema_delete_all | bool or itemin._schema_delete_curr | bool)
