---
- name: "Delete schemas for {{ itemin._subject_name }}"
  ansible.builtin.include_tasks: _schema_delete.yml
  vars:
    _subject_name: "{{ itemin._subject_name }}"
    _schema_delete_curr: "{{ itemin._schema_delete_curr }}"
    _schema_delete_all: "{{ itemin._schema_delete_all }}"
  when: itemin._schema_delete_curr | bool or itemin._schema_delete_all | bool
