---
# connectivity variables
connectors_server_url: https://connect.confluent.io:8083
connectors_user: user
connectors_user_password: user-secret

connectors_dump_file: false
connectors_dump_destination: ./connectors_dump_out.yml
connectors: []

# global variables
connectors_current: []
connectors_to_add: []
connectors_to_delete: []
# destructive - must be explicitly enabled per run/inventory
connectors_delete_enabled: false
